# Generated by Django 4.2.1 on 2023-05-15 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seller1',
            table='seller_tb',
        ),
    ]
