# Generated by Django 4.2.1 on 2023-05-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_alter_seller1_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer_tb',
        ),
    ]
