# Generated by Django 4.2.1 on 2023-05-15 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce_app', '0002_alter_seller1_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('code', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='product/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.seller1')),
            ],
            options={
                'db_table': 'product_tb',
            },
        ),
    ]
